CREATE TABLE T_COVID_CASES_GER (
    PROVINCE             VARCHAR2(4000),
    LAT                  NUMBER,
    LONGI                NUMBER,
    DAY_OCC              DATE,
    VALUE_CONFIRMED      NUMBER,
    VALUE_CONFIRMED_BE   NUMBER,
    VALUE_RECOVERED      NUMBER,
    VALUE_RECOVERED_BE   NUMBER,
    VALUE_DEATHS         NUMBER,
    VALUE_DEATHS_BE      NUMBER,
    VALUE_ACTIVE         NUMBER,
    VALUE_ACTIVE_BE      NUMBER,
    POPULATION           NUMBER,
    UPDATED_ON           DATE
);

ALTER TABLE T_COVID_CASES_GER ADD CONSTRAINT T_COVID_CASES_GER_PK PRIMARY KEY ( PROVINCE, DAY_OCC );

CREATE INDEX T_COVID_CASES_GER_IDX1 ON
    T_COVID_CASES_GER (
        DAY_OCC
    );

CREATE TABLE T_COVID_CASES_INT (
    COUNTRY              VARCHAR2(4000),
    LAT                  NUMBER,
    LONGI                NUMBER,
    DAY_OCC              DATE,
    VALUE_CONFIRMED      NUMBER,
    VALUE_CONFIRMED_BE   NUMBER,
    VALUE_RECOVERED      NUMBER,
    VALUE_RECOVERED_BE   NUMBER,
    VALUE_DEATHS         NUMBER,
    VALUE_DEATHS_BE      NUMBER,
    VALUE_ACTIVE         NUMBER,
    VALUE_ACTIVE_BE      NUMBER,
    COUNTRY_SHORT        VARCHAR2(50),
    POPULATION           NUMBER,
    UPDATED_ON           DATE
);

ALTER TABLE T_COVID_CASES_INT ADD CONSTRAINT T_COVID_CASES_INT_PK PRIMARY KEY ( COUNTRY, DAY_OCC );

CREATE INDEX T_COVID_CASES_INT_IDX1 ON
    T_COVID_CASES_INT (
        DAY_OCC
    );